// idl/audio.idl - WebIDL definition for AudioContext and broaudio engine

/**
 * @file audio.idl
 * @description Web Audio API compatible AudioContext, DSP nodes, synthesis, and streaming.
 */

dictionary AudioDecodedBuffer {
  Float32Array samples;
  long channels;
  long sampleRate;
  long numFrames;
};

dictionary StreamStats {
  long long decodedFrames;
  long long playedFrames;
  long long bufferedFrames;
  long long underrunFrames;
  boolean finished;
};

dictionary StreamFromFileOptions {
  long ringFrames;
  long prebufferFrames;
  boolean loop;
  double gain;
};

dictionary SequenceNote {
  double beat;
  long note;
  double velocity;
  double duration;
};

dictionary SequenceAutomationPoint {
  double beat;
  double value;
};

dictionary MidiPort {
  long index;
  DOMString name;
};

dictionary MidiRawEvent {
  DOMString type;
  long channel;
  long data1;
  long data2;
  long pitchBend;
  double timestamp;
};

dictionary MediaStreamConstraints {
  boolean audio;
};

interface AudioParam {
  attribute double value;

  void setValueAtTime(double value, double time);
  void linearRampToValueAtTime(double value, double time);
  void exponentialRampToValueAtTime(double value, double time);
  void setTargetAtTime(double target, double startTime, double timeConstant);
  void setValueCurveAtTime(Float32Array values, double startTime, double duration);
  void cancelScheduledValues(double cancelTime);
  void cancelAndHoldAtTime(double cancelTime);
};

interface OscillatorNode {
  attribute DOMString type;
  readonly attribute AudioParam frequency;
  readonly attribute AudioParam detune;

  void start(optional double when = 0);
  void stop(optional double when = 0);
  void connect(object destination);
  void disconnect();
};

interface GainNode {
  readonly attribute AudioParam gain;

  void connect(object destination);
  void disconnect();
};

interface BiquadFilterNode {
  attribute DOMString type;
  readonly attribute AudioParam frequency;
  readonly attribute AudioParam detune;
  readonly attribute AudioParam Q;
  readonly attribute AudioParam gain;

  void connect(object destination);
  void disconnect();
  void getFrequencyResponse(Float32Array frequencyHz, Float32Array magResponse, Float32Array phaseResponse);
};

interface AnalyserNode {
  attribute long fftSize;
  readonly attribute unsigned long frequencyBinCount;
  attribute double minDecibels;
  attribute double maxDecibels;
  attribute double smoothingTimeConstant;

  void getFloatFrequencyData(Float32Array array);
  void getByteFrequencyData(Uint8Array array);
  void getFloatTimeDomainData(Float32Array array);
  void getByteTimeDomainData(Uint8Array array);
  void connect(object destination);
  void disconnect();
};

interface MediaStream {
  readonly attribute boolean active;
};

interface MediaStreamAudioSourceNode {
  void connect(object destination);
  void disconnect();
};

interface AudioDestinationNode {
  readonly attribute unsigned long maxChannelCount;
};

interface VoiceAllocator {
  long noteOn(long note, double velocity);
  void noteOff(long note);
  void allNotesOff();
  long voiceCount();
};

interface ModMatrix {
  void setRouting(DOMString source, DOMString dest, double amount);
  double getRouting(DOMString source, DOMString dest);
  void clear();
};

interface MidiInput {
  sequence<MidiPort> listPorts();
  boolean openPort(long index);
  void closePort();
  sequence<MidiRawEvent> pollEvents();
};

interface Sequence {
  attribute double tempo;
  attribute double length;
  attribute boolean loop;

  void addNote(double beat, long note, double velocity, double duration);
  void clearNotes();
  sequence<SequenceNote> getNotes();
};

[cpp_namespace="bro::js"]
interface AudioContext {
  constructor();

  readonly attribute double currentTime;
  readonly attribute long sampleRate;
  readonly attribute DOMString state;
  readonly attribute AudioDestinationNode destination;

  OscillatorNode createOscillator();
  GainNode createGain();
  BiquadFilterNode createBiquadFilter();
  AnalyserNode createAnalyser();
  MediaStreamAudioSourceNode createMediaStreamSource(MediaStream stream);
  VoiceAllocator createVoiceAllocator(long maxVoices);
  ModMatrix createModMatrix();
  MidiInput createMidiInput();
  Sequence createSequence();

  void suspend();
  void resume();
  void close();

  void startRecording();
  Float32Array? stopRecording();

  long createClipFromFile(DOMString path);
  AsyncHandle createClipFromFileAsync(DOMString path);
  AudioDecodedBuffer? decodeAudioData(ArrayBuffer buffer);
  AudioDecodedBuffer? decodeAudioFile(DOMString path);
  boolean exportRecordingToWav(DOMString path);
  boolean saveWav(DOMString path, Float32Array samples, long channels, long sampleRate);

  long createClip(Float32Array samples, optional long channels = 1);
  void deleteClip(long id);
  long getClipSampleCount(long id);
  long getClipChannels(long id);
  Float32Array? getClipWaveform(long id, long points);

  long playClip(long id, optional double gain = 1.0, optional boolean loop = false, optional double pan = 0.0);
  long createStream(long channels, long sampleRate);
  boolean pushStreamSamples(long id, Float32Array samples);
  void closeStream(long id);
  long createStreamFromFile(DOMString path, optional StreamFromFileOptions opts);
  StreamStats? getStreamStats(long id);

  void stopPlayback(long id);
  void setPlaybackGain(long id, double gain);
  void setPlaybackLoop(long id, boolean loop);
  void setPlaybackPlaying(long id, boolean playing);
  void setPlaybackRegion(long id, long startFrame, long endFrame);
  void setPlaybackRate(long id, double rate);
  void setPlaybackPan(long id, double pan);
  double getPlaybackPosition(long id);
  double getPlaybackPositionSeconds(long id);
  void seekPlayback(long id, double seconds);
};
