// tools/check_out_fresh.mjs — Artifact Mirror Freshness Validator
// Regenerates all artifacts (docs, dts, qjs, bronze_host, stubs) to a temporary directory
// and asserts byte-exact / line-exact match against committed out/ files with 0 drift.

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { runEmitDocs } from '../gen/emit_docs.mjs';
import { runEmitDts } from '../gen/emit_dts.mjs';
import { runEmitCAbi } from '../gen/emit_c_abi.mjs';
import { runEmitBronzeHost } from '../gen/emit_bronze_host.mjs';
import { runEmitStubs } from '../gen/emit_stubs.mjs';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const ROOT = path.resolve(__dirname, '..');
const OUT_DIR = path.join(ROOT, 'out');

function normalizeContent(str) {
  return str.replace(/\r\n/g, '\n').trimEnd();
}

function findFiles(dir, baseDir = dir) {
  const files = [];
  if (!fs.existsSync(dir)) return files;
  const entries = fs.readdirSync(dir, { withFileTypes: true });
  for (const entry of entries) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      files.push(...findFiles(full, baseDir));
    } else if (entry.isFile()) {
      files.push({
        fullPath: full,
        relPath: path.relative(baseDir, full).replace(/\\/g, '/'),
      });
    }
  }
  return files;
}

export function runCheckOutFresh() {
  console.log('╔════════════════════════════════════════════════════════════════════╗');
  console.log('║       brosurface Artifact Freshness & Mirror Verification          ║');
  console.log('╚════════════════════════════════════════════════════════════════════╝\n');

  const tempDir = path.join(ROOT, `out_fresh_check_${Date.now()}`);
  fs.mkdirSync(tempDir, { recursive: true });

  try {
    console.log(`[Step 1] Regenerating all 5 artifact targets into temporary staging: ${tempDir}...`);

    // 1. Docs
    runEmitDocs('idl/', path.join(tempDir, 'docs/'));

    // 2. TypeScript defs
    runEmitDts('idl/', path.join(tempDir, 'bro.d.ts'));

    // 3. C-ABI
    runEmitCAbi('idl/', path.join(tempDir, 'c_abi/'));

    // 4. Bronze Host TUs & Manifest
    runEmitBronzeHost('idl/', path.join(tempDir, 'bronze_host/'));

    // 5. Availability Stubs
    runEmitStubs('idl/', path.join(tempDir, 'stubs/feature_stubs.cpp'));

    console.log('\n[Step 2] Comparing staged artifacts against committed out/ tree...');
    const stagedFiles = findFiles(tempDir);
    const drifts = [];

    for (const file of stagedFiles) {
      const outTarget = path.join(OUT_DIR, file.relPath);
      if (!fs.existsSync(outTarget)) {
        drifts.push({
          relPath: file.relPath,
          reason: 'Missing in out/',
        });
        continue;
      }

      const stagedContent = normalizeContent(fs.readFileSync(file.fullPath, 'utf8'));
      const outContent = normalizeContent(fs.readFileSync(outTarget, 'utf8'));

      if (stagedContent !== outContent) {
        drifts.push({
          relPath: file.relPath,
          reason: `Content drift (${stagedContent.split('\n').length} staged lines vs ${outContent.split('\n').length} out/ lines)`,
        });
      }
    }

    // Also check for obsolete files in out/ under tracked artifact subdirectories
    const monitoredSubdirs = ['docs', 'c_abi', 'bronze_host', 'stubs'];
    for (const subdir of monitoredSubdirs) {
      const outSubdir = path.join(OUT_DIR, subdir);
      if (fs.existsSync(outSubdir)) {
        const existingOutFiles = findFiles(outSubdir, OUT_DIR);
        for (const outF of existingOutFiles) {
          const stagedCounterpart = path.join(tempDir, outF.relPath);
          if (!fs.existsSync(stagedCounterpart) && !outF.relPath.includes('test_m6_harness')) {
            drifts.push({
              relPath: outF.relPath,
              reason: 'Orphan/stale file present in out/ but not generated by emitters',
            });
          }
        }
      }
    }

    if (drifts.length > 0) {
      console.error(`\n❌ FRESHNESS CHECK FAILED: Found ${drifts.length} drifted artifact(s) in out/:\n`);
      for (const d of drifts) {
        console.error(`  - out/${d.relPath}: ${d.reason}`);
      }
      console.error(`\nRun emitters to synchronize out/ mirror.`);
      return false;
    }

    console.log(`\n✅ ALL ARTIFACTS FRESH: ${stagedFiles.length} generated artifact(s) match out/ byte-for-byte with 0 drift.\n`);
    return true;
  } finally {
    if (fs.existsSync(tempDir)) {
      try {
        fs.rmSync(tempDir, { recursive: true, force: true });
      } catch (_) {}
    }
  }
}

const isDirect = process.argv[1] && path.resolve(process.argv[1]) === path.resolve(__filename);
if (isDirect) {
  const ok = runCheckOutFresh();
  if (!ok) {
    process.exit(1);
  }
}
